import { Panel } from '../types';

export interface ExportResult {
  success: boolean;
  outputPath?: string;
  message: string;
  error?: string;
}

export class AnimaticExporter {
  async export(panels: Panel[], fps = 24): Promise<ExportResult> {
    console.log('[Animatic] export() called, panels:', panels.length, 'electronAPI:', !!(window as any).electronAPI);

    const panelsWithImages = panels.filter((p) => p.generatedImagePath || p.generatedImageData);
    if (panelsWithImages.length === 0) {
      return {
        success: false,
        message: 'No generated panels to export',
        error: 'Generate at least one panel before exporting',
      };
    }

    try {
      // Use Electron IPC to handle file operations
      const electronAPI = (window as unknown as { electronAPI?: {
        exportAnimatic: (panels: Panel[], outputPath: string | null, fps: number) => Promise<ExportResult>;
        showExportDialog: (options: object) => Promise<{ canceled: boolean; filePath?: string }>;
        openFolder: (path: string) => void;
      } }).electronAPI;

      if (!electronAPI) {
        return {
          success: false,
          message: 'Electron API not available',
          error: 'Running outside of Electron',
        };
      }

      if (!electronAPI.exportAnimatic) {
        console.error('[Animatic] electronAPI.exportAnimatic is undefined — check preload.js exposes it');
        return {
          success: false,
          message: 'exportAnimatic not available',
          error: 'electronAPI.exportAnimatic is undefined',
        };
      }

      const dialogResult = await electronAPI.showExportDialog({
        title: 'Export Animatic',
        defaultPath: 'animatic.mp4',
        filters: [
          { name: 'Video', extensions: ['mp4'] },
          { name: 'All Files', extensions: ['*'] },
        ],
      });

      if (dialogResult.canceled || !dialogResult.filePath) {
        return { success: false, message: 'Export cancelled' };
      }

      const result = await electronAPI.exportAnimatic(panelsWithImages, dialogResult.filePath, fps);

      if (result.success && result.outputPath) {
        electronAPI.openFolder(result.outputPath);
      }

      return result;
    } catch (error) {
      return {
        success: false,
        message: 'Export failed',
        error: error instanceof Error ? error.message : 'Unknown error',
      };
    }
  }

  generateBlenderScript(panels: Panel[], outputPath: string, fps: number): string {
    // Blender Python script template — will be used in Phase 2
    const imagePaths = panels
      .filter((p) => p.generatedImagePath)
      .map((p, i) => `  ("${p.generatedImagePath}", ${p.duration})`)
      .join(',\n');

    return `
import bpy

# Imagginary — Animatic Export Script
# Generated by Imagginary

fps = ${fps}
output_path = "${outputPath}"

panels = [
${imagePaths}
]

# Setup scene
scene = bpy.context.scene
scene.render.fps = fps
scene.render.image_settings.file_format = 'FFMPEG'
scene.render.ffmpeg.format = 'MPEG4'
scene.render.ffmpeg.codec = 'H264'
scene.render.resolution_x = 1920
scene.render.resolution_y = 1080
scene.render.filepath = output_path

# Setup VSE
scene.sequence_editor_create()
seq_editor = scene.sequence_editor

channel = 1
current_frame = 1

for image_path, duration_seconds in panels:
    duration_frames = int(duration_seconds * fps)
    strip = seq_editor.sequences.new_image(
        name=f"panel_{current_frame}",
        filepath=image_path,
        channel=channel,
        frame_start=current_frame
    )
    strip.frame_final_duration = duration_frames
    current_frame += duration_frames

scene.frame_start = 1
scene.frame_end = current_frame - 1

# Render
bpy.ops.render.render(animation=True)
print(f"Animatic rendered to: {output_path}")
`.trim();
  }
}

export const animaticExporter = new AnimaticExporter();
